### ISSUE TITLE
Breaks 'Quick Add Next ⌘D'

### ISSUE THREAD

**Issue by willcalderbank** [pichillilorenzo/JavaScriptEnhancements#10]
I believe the plugin has broken the 'quick add next' feature, default to sublime.   Instead of selecting and jumping to the next occurrence of the current selection, it selects the next occurrence scrolls the page down then scrolls back up to the original selection.

I've looked in the key map doesn't seem to be a keymap clash.

I'm running sublime 3, Build 3143

Edit: The Quick Add Next feature still works in non-JS files

**Comment by pichillilorenzo** [comment]
@willcalderbank Ok i'm going to check about it! 👍

**Comment by pichillilorenzo** [comment]
@willcalderbank I checked it but it works normally on my machine. I use Sublime Text 3 build 3143 and I have Mac OS X (macOS High Sierra, 10.13.2).

Are you sure that is my plugin and not another one that cause this(try to uninstall it and check if it works without my plugin on JS files)?? 
However what is your OS? and could you paste here the console logs of Sublime Text (`View > Show Console`)? Thanks for the support!

**Comment by willcalderbank** [comment]
Im running a Mac still on El Capitan 10.11.6

Ive uninstalled it and it seems to be working ok, on closer investigation it doesnt happen on every selection, only seems to be happening when the new highlighted selection (the one selected by 'quick add next') expression matches the original selection. For example this.foo, highlighting foo then hitting 'quick add next', if the found selection is this.foo it will jump back to the original, if its 'foobar' it wont. 

Its hard to tell but it also only seems to be broken when selection thing off of 'this' in a ES6 class.

The console doesnt print anything.

**Comment by pichillilorenzo** [comment]
@willcalderbank mmm ok.. It is very strange because i didn't attach anything with that key combination (just see the default key settings 👍).. I Will try to reproduce the bug, but maybe could be a bug of Sublime Text self.

**Comment by pichillilorenzo** [comment]
@willcalderbank nothing, I can't reproduce this bug. Could you post here a gif or a video with the example which you are having problems with? Thanks!

**Comment by pichillilorenzo** [comment]
Hi @willcalderbank did you have any news about that?? Thanks
