### ISSUE TITLE
PHP breaks autocompletions

### ISSUE THREAD

**Issue by FeBe95** [pichillilorenzo/JavaScriptEnhancements#16]
### Expected Behavior
JS autocompletions work side by side with PHP code

### Actual Behavior
no autocompletions

### Sublime Text console logs 
none

### Screenshots
![ezgif-1-18ce68ef00](https://user-images.githubusercontent.com/7470739/35189490-b791ab3c-fe4b-11e7-9250-bee1751a5eaf.gif)

### Sample code
```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="initial-scale=1, user-scalable=no">
        <title>title</title>
    </head>
    <body>
        <script type="text/javascript">
            var data = [ <?php require "data.php";?> ];
            
            new Date().get
        </script>
    </body>
</html>
```
### Specifications

- Sublime Text 3 build: 3143
- OS: Windows x64
- JavaScript Enhancements version: 0.13.11

**Comment by pichillilorenzo** [comment]
This is because Flow doesn't recognize PHP code, so I think it can't never work with it in the same context! 😞
