### ISSUE TITLE
Unused variables

### ISSUE THREAD

**Issue by FeBe95** [pichillilorenzo/JavaScriptEnhancements#18]
### Expected Behavior
Used variables are not underlined

### Actual Behavior
used variables are underlined in some cases

### Screenshots
![grafik](https://user-images.githubusercontent.com/7470739/35189605-80d0b8d8-fe4e-11e7-90b2-cef463ffe47a.png)
but:
![grafik](https://user-images.githubusercontent.com/7470739/35189610-a9f60650-fe4e-11e7-9944-85058b9c2c2b.png)

### Specifications

- Sublime Text 3 build: 3143
- OS: Windows x64
- JavaScript Enhancements version: 0.13.11

**Comment by pichillilorenzo** [comment]
@FeBe95 Now it should work, also for #17!

**Comment by andrefgneves** [comment]
@pichillilorenzo, can you please publish the new release on PackageControl?

**Comment by pichillilorenzo** [comment]
@andrefgneves I have already published the release! Now we need just to wait that Package Control will update the reference! I think we need to wait only some minutes (Packages that publishes every week are checked every 2 hours by Package Control, or something like that). 

The last seen now is about 2 hours ago, but i think it is going to re-check again soon 😄

**Comment by andrefgneves** [comment]
Awesome, thanks.
