### ISSUE TITLE
The plugin is finally on Package Control!

### ISSUE THREAD

**Issue by pichillilorenzo** [pichillilorenzo/JavaScriptEnhancements#19]
This plugin has been finally published on Package Control!

**Comment by stefanosandes** [comment]
Very cool plugin, but so hard to make it work =/

The problem with node path is so complicated to solve. I tried with nvm, installation from package, brew.. and I configure custom paths as  in the wiki but nothing make it to work propertly.

In the console I have this output:


```
JavaScript Enhancements plugin version: 0.13.12
node.js version: v9.4.0

env: node: No such file or directory
Package Control: Skipping automatic upgrade, last run at 2018-01-22 22:07:48, next run at 2018-01-22 23:07:48 or after
environment variables loaded using: /bin/zsh -l
```

**Comment by pichillilorenzo** [comment]
@stefanosandes it seems that node.js is recognized but not npm! So, could you post here your plugin settings? In this way I can see if there is a problem with your configuration! Thanks

**Comment by stefanosandes** [comment]
@pichillilorenzo sure, here is:

```
{
	"PATH": "",	
 	"node_js_custom_path": "/Users/stefanosandes/.nvm/versions/node/v9.4.0/bin/node",
 	"npm_custom_path": "/Users/stefanosandes/.nvm/versions/node/v9.4.0/bin/npm",
}
```

**Comment by pichillilorenzo** [comment]
I have installed the same version of node.js and npm and it works as expected. I have Mac OS High Sierra 10.13.2.
What is the error that shows to you? Could you post a screenshot?

Moreover, if you try to execute `npm install` in the plugin folder (`Preferences > Browse Packages... > JavaScript Enhancements`), does it work? Or it needs also the `sudo` prefix?

**Comment by stefanosandes** [comment]
I'm using High Sierra 10.13.2 too.

Ok, I ran `npm install` from plugin folder and all done without problems, and `sudo` was not needed.

I'm still getting the message:

![documento_em_branco_do_skitch](https://user-images.githubusercontent.com/6722075/35253484-cc8103b2-ffcc-11e7-9fc1-8eb59df1b54b.png)

The console output keep the same as I posted before.

**Comment by pichillilorenzo** [comment]
@stefanosandes It is really strange! it does not make sense.. I think it is something related to the global PATH variable environment, but I'm not sure! The error is `env: node: No such file or directory`. Could you try this https://stackoverflow.com/questions/43465086/env-node-no-such-file-or-directory-in-mac?? 

Thanks!

**Comment by stefanosandes** [comment]
@pichillilorenzo I found the problem. In TerminalView, when I type `echo $PATHS` the output is:

```
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/usr/local/share/dotnet:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands 
```

But when I type it in Terminal, the output is:

```
/Users/stefanosandes/.npm-packages/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/usr/local/share/dotnet:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/stefanosandes/.nvm/versions/node/v9.4.0/bin:/Users/stefanosandes/.antigen/bundles/robbyrussell/oh-my-zsh/lib:/Users/stefanosandes/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/git:/Users/stefanosandes/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/command-not-found:/Users/stefanosandes/.antigen/bundles/zsh-users/zsh-syntax-highlighting:/Users/stefanosandes/.antigen/bundles/zsh-users/zsh-autosuggestions:/Users/stefanosandes/.antigen/bundles/mafredri/zsh-async:/Users/stefanosandes/.antigen/bundles/sindresorhus/pure
```

The second output includes node path.

It make sense for u?

**Comment by pichillilorenzo** [comment]
TerminalView is separated from this plugin! For some commands, like in this case, I use the [subprocess](https://docs.python.org/3.3/library/subprocess.html) python 3 module directly.
However I have just noticed that I have missed the `:` at the begin of PATH value in the configuration that i have gave to you. 
So try again with this (notice the `:` at the begin of PATH value):

```json
{
        "PATH": ":/Users/stefanosandes/.nvm/versions/node/v9.4.0/bin",	
 	"node_js_custom_path": "node",
 	"npm_custom_path": "npm"
}
```

With this, I think that the PATH is correctly setted now! It will add the path of node.js v9.4.0 and npm binaries, like in your Terminal. Let me know if this works!

**Comment by stefanosandes** [comment]
@pichillilorenzo sorry, but a tried in another way and I cant test in the previous environment because I've made some changes. I followed this steps:

1. Uninstall ZSH
2. Create a `.bashrc`
3. Run `install.sh` script that come with nvm (it added some lines in `.bashrc`)
4. Add `source ~/.bashrc` to `.bash_profile`
5. Add node to PATH

Then, I tried to run sublime, but I had then same problem. After some adjusts in Javascript Enhancements settings all works fine and the I'm not getting the message anymore.

My settings look like this:

```
{
	"PATH": "",
	"node_js_custom_path": "/Users/stefanosandes/.nvm/versions/node/v9.4.0/bin/node",
	"npm_custom_path": "/Users/stefanosandes/.nvm/versions/node/v9.4.0/bin/npm",
}
```

I'll try to install zsh again.

**Comment by pichillilorenzo** [comment]
So do you think is a shell problem?

**Comment by stefanosandes** [comment]
@pichillilorenzo  I'll do more tests in other Mac and I'll provide feedback here soon.

**Comment by pichillilorenzo** [comment]
@stefanosandes I tested it and the problem is the **zsh** shell.. I'm going to update the plugin to force "/bin/bash" shell!

**Comment by tr1s** [comment]
You know what, now that I'm reading all this, I have the same problem as you @stefanosandes , **did you get this fixed**?

@pichillilorenzo when I type `subl .` in the terminal I don't get the pop-up. It's only when opening from the app. I've tried filling the custom path in Global and Custom and it still doesn't work. 

Any more suggestions? This is after the latest update you just did!

**Comment by pichillilorenzo** [comment]
@tr1s this is strange.. it seems that bash shell doesn't have the node.js and npm path. However I will try to get it work incorporating fix with **Fix Mac Path** plugin code!

**Comment by pichillilorenzo** [comment]
Done! with version 0.13.16 now I think it will works without setting the PATH value and using directly the default plugin settings! Let me know, thanks!

**Comment by tr1s** [comment]
@pichillilorenzo Perfect. All done and working beautifully with no pop-ups. Thanks so much for your swift debugging and help!
