### ISSUE TITLE
Unused variable shows up in React project

### ISSUE THREAD

**Issue by xihaoxiaohao** [pichillilorenzo/JavaScriptEnhancements#20]
### Sublime Text console logs 
```
JavaScript Enhancements plugin version: 0.13.12
node.js version: v8.9.3
npm version: 5.5.1
Package Control: Skipping automatic upgrade, last run at 2018-01-22 13:26:18, next run at 2018-01-22 14:26:18 or after
```

### Screenshots
<img width="489" alt="a" src="https://user-images.githubusercontent.com/9826637/35246792-cc508890-ff7c-11e7-941a-178e87b36a3a.png">

### Specifications

- Sublime Text 3 build: 3143
- OS: Mac OS Sierra
- JavaScript Enhancements version: 0.13.12

**Comment by pichillilorenzo** [comment]
@xihaoxiaohao Thanks! I'm updating it right now to solve this issue!

**Comment by pichillilorenzo** [comment]
Now with the 0.13.13 version it should work!

**Comment by xihaoxiaohao** [comment]
after upgrading and restart sublime, still not working:
<img width="487" alt="a" src="https://user-images.githubusercontent.com/9826637/35262281-d2e7398c-ffc8-11e7-9e1e-16efe83d2726.png">
<img width="716" alt="b" src="https://user-images.githubusercontent.com/9826637/35262286-d5301e7a-ffc8-11e7-8440-bd0d1c9d1352.png">

**Comment by pichillilorenzo** [comment]
@xihaoxiaohao I have updated the plugin now to the 0.13.14 version! Let me know if it works. Thanks!

**Comment by xihaoxiaohao** [comment]
It's working now, thanks!
