### ISSUE TITLE
Another unused variable bug

### ISSUE THREAD

**Issue by ilearnio** [pichillilorenzo/JavaScriptEnhancements#22]
<img width="409" alt="1" src="https://user-images.githubusercontent.com/14331216/35274105-8e319b72-0043-11e8-9ccc-fb31597eb01a.png">

**Comment by ilearnio** [comment]
And another one 

<img width="668" alt="2" src="https://user-images.githubusercontent.com/14331216/35274902-930c9c7a-0046-11e8-8f94-98615c166053.png">

**Comment by ilearnio** [comment]
Would be nice if there will be an option to disable unused variables check since I have SublimeLinter + eslint which does that already.

**Comment by pichillilorenzo** [comment]
@ilearnio yeah I will add it 👍

**Comment by ilearnio** [comment]
Awesome! Thanks for such a super great plugin!

**Comment by pichillilorenzo** [comment]
@ilearnio Done! Now it should work. Moreover, if you want, you can disable this feature with: `"enable_unused_variables_feature": false` in the plugin settings. Thanks for the support!

**Comment by ilearnio** [comment]
Wow. Thanks! I will try to test it once the new version will appear in package control
