### ISSUE TITLE
Javascript Enhancements broke even though it was working

### ISSUE THREAD

**Issue by ninja542** [pichillilorenzo/JavaScriptEnhancements#23]
### Actual Behavior
I got the plugin to work, but then I think it updated itself, and I get this error:

### Sublime Text console logs 
```
Traceback (most recent call last):
  File "C:\Users\Claudia Chen\AppData\Roaming\Sublime Text 3\Packages\JavaScript Enhancements\_generated_2018_01_23_at_15_18_32.py", line 244, in execute_check_output
    args, shell=True, stderr=subprocess.STDOUT, timeout=10
  File "./python3.3/subprocess.py", line 589, in check_output
subprocess.CalledProcessError: Command '"C:\\Users\\Claudia Chen\\AppData\\Roaming\\Sublime Text 3\\Packages\\JavaScript Enhancements\\node_modules\\.bin\\flow.cmd" "autocomplete" "--from" "sublime_text" "--root" "C:\\Users\\Claudia Chen\\AppData\\Roaming\\Sublime Text 3\\Packages\\JavaScript Enhancements\\flow" "--json" null < "c:\\users\\claudi~1\\appdata\\local\\temp\\tmp9i38d1"' returned non-zero exit status 1

b'The system cannot find the path specified.\r\n'
```
### Steps to Reproduce the Problem

1. Installed the plugin and this happened, I didn't change anything (I did disable and reenable SublimeLinter, I don't think that would affect this plugin though)
1. I also tried fixing the PATH, but I still get the same error

### Specifications

- Sublime Text 3 build: 3143
- OS: Windows
- JavaScript Enhancements version: 0.13.14

**Comment by ninja542** [comment]
After disabling and enabling the plugin, Javascript Enhancements does show my npm and node.js version, but then proceeds to spit out that console message when I select Javascript Next as my syntax language

**Comment by pichillilorenzo** [comment]
@ninja542 I tried it on Windows 10 with Sublime Text 3 build 3143, and after upgrading to 0.13.14 from 0.13.13, it works like expected! 
If you look into the plugin folder, can you see `node_modules\.bin\flow.cmd` file??

**Comment by ninja542** [comment]
I couldn't find the file, so I uninstalled and reinstalled the package, and everything works now. 

I didn't delete anything from the package so I find that a little weird. Thank you for helping me!

**Comment by pichillilorenzo** [comment]
I don't know why it happened 🤔

**Comment by ninja542** [comment]
I shut down my computer and today I'm working on my javascript files, and the node_modules folder is empty for some strange reason.

Although I didn't check the node_modules folder after the plugin updated

**Comment by pichillilorenzo** [comment]
@ninja542 mmm ok I checked on Windows and I get the same problem.. I'm going to check about that!

**Comment by pichillilorenzo** [comment]
@ninja542 I think that now, with version 0.13.17, it should work! Also when the plugin will be upgraded!

**Comment by glockjt** [comment]
Just installed today and got this same error.

**Comment by pichillilorenzo** [comment]
@glockjt What exactly? Can you post the Sublime Text console logs please?

**Comment by glockjt** [comment]
```
JavaScript Enhancements plugin version: 0.16.15
node.js version: v6.10.0
Traceback (most recent call last):
  File "/Users/jglock/Library/Application Support/Sublime Text 3/Packages/JavaScript Enhancements/src/libs/node.py", line 112, in execute_check_output
    args, shell=True, stderr=subprocess.STDOUT, timeout=10
  File "./python3.3/subprocess.py", line 589, in check_output
subprocess.CalledProcessError: Command '/usr/local/bin/node '/Users/jglock/Library/Application Support/Sublime Text 3/Packages/JavaScript Enhancements/node_modules/.bin/flow' ast --from sublime_text < /var/folders/r1/7wtlplvs3_zfd1gfbbrw3nlc0000gp/T/javascript_enhancements_7k0gb4' returned non-zero exit status 1

b"internal/child_process.js:313\n    throw errnoException(err, 'spawn');\n    ^\n\nError: spawn EACCES\n    at exports._errnoException (util.js:1022:11)\n    at ChildProcess.spawn (internal/child_process.js:313:11)\n    at exports.spawn (child_process.js:380:9)\n    at Object.<anonymous> (/Users/jglock/Library/Application Support/Sublime Text 3/Packages/JavaScript Enhancements/node_modules/flow-bin/cli.js:14:3)\n    at Module._compile (module.js:570:32)\n    at Object.Module._extensions..js (module.js:579:10)\n    at Module.load (module.js:487:32)\n    at tryModuleLoad (module.js:446:12)\n    at Function.Module._load (module.js:438:3)\n    at Module.runMain (module.js:604:10)\n"
npm version: 5.4.0
```

**Comment by pichillilorenzo** [comment]
@glockjt Ok, so you have a different error that is related to some access permission!
I strongly recommend you to install node.js and npm using something like [nvm](https://github.com/creationix/nvm). 
Otherwise try to follow this: https://stackoverflow.com/questions/25258361/npm-wont-install-any-package-on-mac-new-clean-build-eacces-other-errors

Let me know! Thanks!
