### ISSUE TITLE
Pop-up will not go away - zsh shell doesn't recognize node.js

### ISSUE THREAD

**Issue by tr1s** [pichillilorenzo/JavaScriptEnhancements#25]
### Expected Behavior

Expected behaviour works. I'm getting the completions. I re-installed node and npm through Homebrew, and now I can't get rid of this pop-up. I tried uninstalling and re-installing (now through package contorl), but still didn't help. **How do I find my custom node path?** I'm googling it and i'm only getting information about npm paths :/ I'm confused.

Edit: I also have nvm installed, but don't really understand how to use it yet. So I have nvm, npm, and node all installed via Homebrew.

Also, why do I update the Global Settings instead of the User Settings?

**Could someone please help me find my node path to put in the Global Settings so I can stop seeing this pop-up?**

Please and thank you.

### Actual Behavior

I get this pop up still.

<img width="484" alt="screen shot 2018-01-24 at 4 52 06 pm" src="https://user-images.githubusercontent.com/19172250/35359219-4070c3d8-0127-11e8-81a8-2cae6ecd64ac.png">

### Sublime Text console logs 

`startup, version: 3143 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/tris/Library/Application Support/Sublime Text 3/Packages
state path: /Users/tris/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/tris/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["CSS", "Vintage"]
pre session restore time: 0.308342
using gpu buffer for window
loading dictionary Packages/Language - English/en_US.dic
using gpu buffer for window
startup time: 0.461342
Error loading CSS.sublime-syntax: Unable to find CSS.sublime-syntax in Packages/HTML/HTML.sublime-syntax
no such context CSS.sublime-syntax#rule-list-body at line 371 column 28 in Packages/HTML/HTML.sublime-syntax
no such context CSS.sublime-syntax#rule-list-body at line 390 column 28 in Packages/HTML/HTML.sublime-syntax
no such context CSS.sublime-syntax#rule-list-body at line 371 column 28 in Packages/HTML/HTML.sublime-syntax
no such context CSS.sublime-syntax#rule-list-body at line 390 column 28 in Packages/HTML/HTML.sublime-syntax
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.50-backrefs
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-pymdownx
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin A File Icon.A File Icon
reloading plugin All Autocomplete.all_views_completions
reloading plugin AutoFileName.autofilename
reloading plugin AutoFileName.getimageinfo
reloading plugin BracketHighlighter.bh_core
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_popup
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin BracketHighlighter.support
reloading plugin Color Highlighter.color_converter
reloading plugin Color Highlighter.color_highlighter
reloading plugin Color Highlighter.color_hover_listener
reloading plugin Color Highlighter.color_scheme
reloading plugin Color Highlighter.color_scheme_color_highlighter
reloading plugin Color Highlighter.color_searcher
reloading plugin Color Highlighter.color_selection_listener
reloading plugin Color Highlighter.colors
reloading plugin Color Highlighter.content_listener
reloading plugin Color Highlighter.convert_color_command
reloading plugin Color Highlighter.css_colors
reloading plugin Color Highlighter.dummy_event_listener
reloading plugin Color Highlighter.gutter_icons_color_highlighter
reloading plugin Color Highlighter.load_resource
reloading plugin Color Highlighter.main
reloading plugin Color Highlighter.path
reloading plugin Color Highlighter.phantoms_color_highlighter
reloading plugin Color Highlighter.pick_color_command
reloading plugin Color Highlighter.regex_compiler
reloading plugin Color Highlighter.regions
reloading plugin Color Highlighter.set_setting_command
reloading plugin Color Highlighter.settings
reloading plugin Color Highlighter.st_helper
reloading plugin Color Highlighter.topsort
reloading plugin ColorSchemeEditor.ColorSchemeEditor-ST2
reloading plugin CSS3.css3_completions
reloading plugin CSS3.rgb_to_hex
reloading plugin DocBlockr.jsdocs
reloading plugin Emmet.emmet-plugin
reloading plugin FuzzyFileNav.fuzzy_file_nav
reloading plugin FuzzyFileNav.multiconf
reloading plugin FuzzyFileNav.notify
reloading plugin FuzzyFilePath.command_goto_file
reloading plugin FuzzyFilePath.command_insert_path
reloading plugin FuzzyFilePath.command_rebuild_cache
reloading plugin FuzzyFilePath.command_replace_region
reloading plugin FuzzyFilePath.command_show_context
reloading plugin FuzzyFilePath.command_show_current_settings
reloading plugin FuzzyFilePath.command_show_info
reloading plugin FuzzyFilePath.completion
reloading plugin FuzzyFilePath.controller
reloading plugin FuzzyFilePath.current_state
reloading plugin FuzzyFilePath.expression
reloading plugin FuzzyFilePath.ProjectListener
reloading plugin FuzzyFilePath.query
reloading plugin FuzzyFilePath.QueryCompletionListener
reloading plugin FuzzyFilePath.TestRunner
reloading plugin FuzzyFilePath.ViewListener
reloading plugin Git.git_commands
reloading plugin GitGutter.plugin
reloading plugin Markdown Preview.helper
reloading plugin Markdown Preview.markdown_settings
reloading plugin Markdown Preview.markdown_wrapper
reloading plugin Markdown Preview.MarkdownPreview
reloading plugin Material Theme.Icons
reloading plugin Material Theme.MT
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin PackageResourceViewer.package_resource_viewer
reloading plugin PackageResourceViewer.package_resources
reloading plugin PackageSync.PackageSync
reloading plugin ScopeHunter.scope_hunter
reloading plugin ScopeHunter.scope_hunter_notify
reloading plugin ScopeHunter.support
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin SyncedSideBar.SyncedSideBar
reloading plugin TerminalView.exec
reloading plugin TerminalView.gateone_terminal_emulator
reloading plugin TerminalView.linux_pty
reloading plugin TerminalView.pyte_terminal_emulator
reloading plugin TerminalView.sublime_terminal_buffer
reloading plugin TerminalView.sublime_view_cache
reloading plugin TerminalView.TerminalView
reloading plugin TerminalView.utils
reloading plugin Theme - Monokai Pro.Monokai Pro
reloading plugin Babel.Babel
reloading plugin HTML-CSS-JS Prettify.HTMLPrettify
reloading plugin JavaScript Enhancements._generated_2018_01_23_at_15_18_32
reloading plugin Minify.Minify
reloading plugin TypeScript.main
2018-01-24 16:51:00,472: 140735619679040: WARNING: TypeScript plugin initialized.
reloading plugin WakaTime.WakaTime
plugins loaded
[WakaTime] [INFO] Initializing WakaTime plugin v8.0.6
Traceback: error.

Output:

Error:
/bin/sh: convert: command not found

Highlighting colors with gutter icons is not supported with current ImageMagick setup. Try configuring the "icon_factory setting"
lang_service_enabled: True
Path of tsserver.js: /Users/tris/Library/Application Support/Sublime Text 3/Packages/TypeScript/tsserver/tsserver.js
Path of tsc.js: /Users/tris/Library/Application Support/Sublime Text 3/Packages/TypeScript/tsserver/tsc.js
Trying to spawn node executable from: /usr/local/bin/node
ref view not found
reloading settings Packages/User/PackageSync.sublime-settings
Emmet: No need to update PyV8
JavaScript Enhancements plugin version: 0.13.14

zsh:1: command not found: node
environment variables loaded using: /bin/zsh -l
Package Control: Skipping automatic upgrade, last run at 2018-01-24 16:00:53, next run at 2018-01-24 17:00:53 or after
AutoFileName: could not find /Users/tris/Library/Application Support/Sublime Text 3/Packages/JavaScript Enhancements/:/
reloading settings Packages/JavaScript Enhancements/JavaScript Enhancements.sublime-settings
reloading settings Packages/JavaScript Enhancements/JavaScript Enhancements.sublime-settings
FuzzyFilePath cached 10 files in /Users/tris/Sites/learning/ReduxSimpleStarter
FuzzyFilePath cached 10 files in /Users/tris/Sites/learning/ReduxSimpleStarter`

### Specifications

- Sublime Text 3 build: 3143 - Latest
- OS: 10.13.3 - Latest
- JavaScript Enhancements version: Latest

**Comment by pichillilorenzo** [comment]
@tr1s to find your node path, you can use `which node` and then set it to custom_node_path. However it seems that `zsh` shell doesn't load node.js path (see #19).. If you could talk now, connect on gitter https://gitter.im/JavaScriptEnhancements/Lobby, so we can try to change something on my code plugin in order to make it work now 😃

**Comment by pichillilorenzo** [comment]
Ok I tested it and the problem is the **zsh** shell.. I'm going to update the plugin to force "/bin/bash" shell!

**Comment by tr1s** [comment]
Hey @pichillilorenzo , yeah I also forgot to mention I just switched to oh my zsh so I guess that's it?

I'm in the lobby!

**Comment by madisonbullard** [comment]
Hi, I am running the latest update, 0.13.15, and just started receiving this same error when my local shell is zsh. When I switch to bash using ```chsh -s /bin/bash ```, the problem goes away. I want to keep using zsh on my machine. Any suggestions? 

Thank you!

**Comment by pichillilorenzo** [comment]
@madisonbullard Could you test the new version 0.13.16 without using the Fix Mac Path plugin to see if now it works to you please? Thanks! 😄

**Comment by madisonbullard** [comment]
@pichillilorenzo It now works both with and without Fix Mac Path. I was also able to remove the user settings file that previously contained ```node_js_custom_path``` and ```npm_custom_path```, and it works with and without Fix Mac Path in that context as well. Good job!

Thanks so much!!!

**Comment by tr1s** [comment]
Nice find @madisonbullard, but glad it's now fixed without the need for an extra plugin!
