### ISSUE TITLE
Not working inside html files

### ISSUE THREAD

**Issue by duranivan** [pichillilorenzo/JavaScriptEnhancements#26]
Thanks for a great plugin. However I have noticed that it is not working inside html scripts (things such as go to definition or autocompletions). Is this the expected behavior?

**Comment by pichillilorenzo** [comment]
@duranivan at least autocompletions must work inside html scripts. Did you get some errors in the sublime text console?

**Comment by duranivan** [comment]
Sorry, my bad, autocompletions are indeed working (just double checked), but go to definition does not. The tooltip does show up and when I click in `go to defition` it just goes to the top of the html file. I am not getting any errors in the st console.

**Comment by pichillilorenzo** [comment]
Yeah I know about that! At the moment it works fine only on javascript files but I will try to support that also in html file 👍

**Comment by duranivan** [comment]
great thanks! Looking forward to it.
