### ISSUE TITLE
Create React App - Could not create a project called "myApp" because of npm naming restrictions

### ISSUE THREAD

**Issue by MarkRabey** [pichillilorenzo/JavaScriptEnhancements#29]
### Expected Behavior
I would expect using "Create JavaScript Project" and selecting "react" would create a React project.

### Actual Behavior
The console displays errors, project is not created.

### Sublime Text console logs 
```
.[!.],}* ./ ; rm -rf myAppct-sublime mark$ create-react-app myApp ; mv ./myApp/{                                                                         
Could not create a project called "myApp" because of npm naming restrictions:                                                                            
  *  name can no longer contain capital letters                                                                                                          
mv: rename ./myApp/.[!.]* to ./.[!.]*: No such file or directory                                                                                         
mv: rename ./myApp/* to ./*: No such file or directory  
```

### Steps to Reproduce the Problem

1. Project > Create JavaScript Project > react

### Specifications

- Sublime Text 3 build:
- OS: OSX High Sierra
- JavaScript Enhancements version: 0.13.17

**Comment by pichillilorenzo** [comment]
@MarkRabey Ok, it is strange because I tested it and I didn't get this error but I will fix it.. This is because I create a temporary folder named "myApp" that will be deleted after the completion of creation process. So I will change the name of this temp folder in "my-app" 👍 . Thanks for the support!

**Comment by pichillilorenzo** [comment]
@MarkRabey Try the new version 0.15.0 and let me know!

**Comment by MarkRabey** [comment]
Works great! Thanks! Great package by the way.
