### ISSUE TITLE
I cant create new javascript project!

### ISSUE THREAD

**Issue by rperrote** [pichillilorenzo/JavaScriptEnhancements#3]
![image](https://user-images.githubusercontent.com/1812230/34487441-1d9cdb24-efb3-11e7-8d01-fef6ebab2996.png)

**Comment by pichillilorenzo** [comment]
Hi @rperrote 

Like is said in the README.md file, the **OS SUPPORTED NOW** are only:
* Linux (64-bit)
* Mac OS X

For Windows there is a dependency, that is the **TerminalView** plugin, that is not available unfortunately for now 😞

**Comment by rperrote** [comment]
Ohh I really like the idea, it hurts man.. :(

**Comment by pichillilorenzo** [comment]
I tried to contact the author of [TerminalView plugin](https://github.com/Wramberg/TerminalView) but I didn't receive any answer about Windows support yet!

**Comment by tofuvn** [comment]
![screenshot from 2018-01-02 17-21-30](https://user-images.githubusercontent.com/34548201/34490851-7a1240dc-efe1-11e7-9719-35c733a51c3f.png)
what wrong here ?

**Comment by pichillilorenzo** [comment]
I don't know.. Please copy and paste here the console log of Sublime Text!

**Comment by ChainsawBaby** [comment]
@pichillilorenzo @tofuvn I got the same error, fixed it by renaming the package folder to "JavaScript Enhancements", that's where it's trying to look for the sublime-settings file, I had it named to "JavaScriptEnhancements" at first

**Comment by pichillilorenzo** [comment]
@ChainsawBaby 

Yeah! You are right! That's because it is the name of the github repo, but when it will be published on Package Control, its name will be "JavaScript Enhancements".

**Comment by pichillilorenzo** [comment]
I have updated the Wiki and the README.md file!

**Comment by pichillilorenzo** [comment]
Hi @rperrote, for Windows support I will create these days a **degraded** mode of this plugin BUT without the use of TerminalView plugin, so WATCH the repository 😃 . Like I said before, TerminalView plugin is not available unfortunately!

**Comment by rperrote** [comment]
Great! Thank you very much! When I start my next project I will surely try it. 
Thanks for the self imposed goal of turning ST into JS IDE!
