### ISSUE TITLE
Evaluate Javascript feature not working in Windows - "The filename, directory name, or volume label syntax is incorrect." error

### ISSUE THREAD

**Issue by iamcaleblol** [pichillilorenzo/JavaScriptEnhancements#32]
### Expected Behavior
The terminal will output some result.

### Actual Behavior
The terminal showed:
```
The filename, directory name, or volume label syntax is incorrect.
The filename, directory name, or volume label syntax is incorrect.
````
### Screenshots
<img width="451" alt="e" src="https://user-images.githubusercontent.com/31832678/35737514-c42b533c-0866-11e8-9d45-58d51ac70d1b.PNG">

### Steps to Reproduce the Problem

1. Select a line of JavaScript code in Sublime Text
2. Right click and select "Evaluate JavaScript"
### Specifications

- Sublime Text 3 build: 3143
- OS: windows 10 64 bit (Windows 7 also doesn't work)
- JavaScript Enhancements version: 
- Node JS version: 9.4.0

**Comment by pichillilorenzo** [comment]
@iamcaleblol I don't have enough information! Could you post a screenshot please? Also, the output terminal is coming from the TerminalView plugin or Sublime Text console log?? Thanks

**Comment by iamcaleblol** [comment]
The terminal is opened in a new window, probably cmd.exe

**Comment by pichillilorenzo** [comment]
ah yeah sorry! Could you post here the absolute path of the file on where you used the command? 
Also, open the Sublime Text console and write these lines, **one at time**:
```python
import tempfile
fp = tempfile.NamedTemporaryFile()
fp.name
```
You will see something like:
![schermata 2018-02-01 alle 15 36 53](https://user-images.githubusercontent.com/5956938/35683988-cdf5deb6-0765-11e8-9cd0-8a808dbef02a.png)
What did you get?

**Comment by iamcaleblol** [comment]
`c:\\users\\`(username)`\\appdata\\local\\temp\\tmpf_brih`

**Comment by pichillilorenzo** [comment]
Ok.. It is weird because I don't see any problems about the paths.. like said here:
 [https://technet.microsoft.com/en-us/library/cc956689.aspx](https://technet.microsoft.com/en-us/library/cc956689.aspx), it is a problem related to a filename or something like that.. if you could provide me also your Username (or in case send me an email with it), I could test it on my Windows system! Maybe it could be a problem on how I escape some characters.

**Comment by iamcaleblol** [comment]
I tried in my Windows 7 computer and it wasn't working also... so I think it's not related to the username nor the path of the file.

**Comment by pichillilorenzo** [comment]
hmmm ok.. then open the folder plugin, open the file `_generated_2018_01_26_at_21_58_40.py`, go to line 2959 and add this code: 

`print([self.cmd] + ( ["-NoExit", "-Command"] if self.cmd.startswith("powershell") else ["/K"] ) + ( ["$Host.UI.RawUI.WindowTitle", "=", self.title] if self.cmd.startswith("powershell") else ["title", self.title] ) + ( [";", "CD", self.cwd] if self.cmd.startswith("powershell") else ["&&", "CD", self.cwd] ) + ( [";"] if self.cmd.startswith("powershell") else ["&&"] ) + cmd_args)`

Then execute the evaluate javascript command again and paste here the console logs of Sublime Text. Thanks! (In my next release I will add an option to enabled debug mode for the plugin)

**Comment by pichillilorenzo** [comment]
I solved it, there was a problem on the command arguments! The fix will be on the new release!

**Comment by pichillilorenzo** [comment]
@iamcaleblol  Try the new version 0.15.0 and let me know!
