### ISSUE TITLE
Can't get updated package to work

### ISSUE THREAD

**Issue by lukakerr** [pichillilorenzo/JavaScriptEnhancements#34]
### Expected Behavior

Before package control I was using v0.1.11, but after updating to the latest version v0.13.17 the package seems to break.

I've installed via package control and also manually and both times I receive the error below. I've tried manually installing npm modules inside the package, I've tried uninstalling and reinstalling the package manually and via package control, I've tried setting different custom PATHs to:

```
"PATH": ":/Users/Luka/.nvm/versions/node/v8.9.1/bin",
```

and

```
"PATH": ":/usr/local/bin",
```

I've also tried setting a custom `"node_js_custom_path"`.

### Sublime Text console logs 
```
Traceback (most recent call last):
  File "/Users/Luka/Library/Application Support/Sublime Text 3/Packages/JavaScript Enhancements/_generated_2018_01_26_at_21_58_40.py", line 246, in execute_check_output
    args, shell=True, stderr=subprocess.STDOUT, timeout=10
  File "./python3.3/subprocess.py", line 589, in check_output
subprocess.CalledProcessError: Command 'node '/Users/Luka/Library/Application Support/Sublime Text 3/Packages/JavaScript Enhancements/node_modules/.bin/flow' check-contents --from sublime_text --root /Users/Luka/dev/hackd --json /Users/Luka/dev/hackd/App.js < /var/folders/7r/ypx2k4pd5jxgyy7kt6wzmv_r0000gn/T/tmpnwaqfz' returned non-zero exit status 8

b'.flowconfig:53 Unsupported option specified! (unsafe.enable_getters_and_setters)\n{"flowVersion":"0.64.0","exit":{"code":8,"reason":"Invalid_flowconfig","msg":".flowconfig:53 Unsupported option specified! (unsafe.enable_getters_and_setters)"}}\n'
```

### Specifications

- Sublime Text 3 build: 3156
- OS: MacOS 10.13.3
- JavaScript Enhancements version: 0.13.17

**Comment by pichillilorenzo** [comment]
The problem is not the package, but your .flowconfig option `unsafe.enable_getters_and_setters`. This option was removed in flow 0.62.0 (See [here](https://github.com/facebook/flow/issues/5594)) and this plugin uses the latest version (0.64.0). 
However in the next release I will show up in the status bar any errors related to the .flowconfig file like this!
