### ISSUE TITLE
could it support the file path on Windows that includes Chinese?

### ISSUE THREAD

**Issue by waiaan** [pichillilorenzo/JavaScriptEnhancements#35]
if the file path include Chinese ,it would be turned into :

it show that Could not find file or directory.
thank you

**Comment by pichillilorenzo** [comment]
mmm the problem is that for Windows I uses `json.dumps()` to escape command arguments because `shlex.quote` won't work.. I will check more about that

**Comment by waiaan** [comment]
thank you

**Comment by pichillilorenzo** [comment]
@waiaan Done, I have just added `ensure_ascii=False` attribute to the `json.dumps()` calls. It will be in the next release. I think that today I can publish it finally!! 👍

**Comment by waiaan** [comment]
great! thank you!

**Comment by pichillilorenzo** [comment]
@waiaan Try the new version 0.15.0 and let me know!

**Comment by waiaan** [comment]
it works now ! thank you
