### ISSUE TITLE
Can't initialize flow

### ISSUE THREAD

**Issue by maprezentalok** [pichillilorenzo/JavaScriptEnhancements#37]
### Expected Behavior
run without exception

### Actual Behavior
exception

### Sublime Text console logs 
DPI scale: 1
startup, version: 3143 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/d/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/d/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/d/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.212378
startup time: 0.253379
first paint time: 0.254379
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin A File Icon.A File Icon
reloading plugin Material Theme.Icons
reloading plugin Material Theme.MT
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "MT in C:\Users\d\AppData\Roaming\Sublime Text 3\Installed Packages\Material Theme.sublime-package", line 1, in <module>
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "utils in C:\Users\d\AppData\Roaming\Sublime Text 3\Installed Packages\Material Theme.sublime-package", line 3, in <module>
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "utils.config in C:\Users\d\AppData\Roaming\Sublime Text 3\Installed Packages\Material Theme.sublime-package", line 8, in <module>
  File "C:\Users\d\AppData\Roaming\SUBLIM~1\Packages\mdpopups\st3\mdpopups\__init__.py", line 27, in <module>
    from . import frontmatter
  File "C:\Users\d\AppData\Roaming\SUBLIM~1\Packages\mdpopups\st3\mdpopups\frontmatter.py", line 2, in <module>
    import yaml
ImportError: No module named 'yaml'
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin JavaScript Enhancements._generated_2018_02_11_at_19_44_22
reloading plugin LocalizedMenu.Localize
plugins loaded
JavaScript Enhancements plugin version: 0.15.0
node.js version: v8.9.4
npm version: 5.6.0
Package Control: Skipping automatic upgrade, last run at 2018-02-23 14:48:09, next run at 2018-02-23 15:48:09 or after
error: Can't initialize flow.

### Screenshots
![paint](https://user-images.githubusercontent.com/32941861/36599285-38050b88-18af-11e8-9fd1-3135fa3049a3.png)

### Steps to Reproduce the Problem

1. open sublime text
1. project tab -> create new javascript project
1. error occurs

### Specifications

- Sublime Text 3 build: 3143
- OS: windows 7 sp1 enterprise n x64 
- JavaScript Enhancements version: 0.15.0

**Comment by pichillilorenzo** [comment]
Open the plugin folder (go to `Preferences > Browse Packages...`), open the _generated_2018_02_11_at_19_44_22.py file, then go to the [2056 line](https://github.com/pichillilorenzo/JavaScriptEnhancements/blob/master/_generated_2018_02_11_at_19_44_22.py#L2056) and add, just before it, this code:

```python 
print(result)
```

So you will have something like:
```python
      ... other code ...

      result = node.execute("flow", ["init"], is_from_bin=True, chdir=path)
      if not result[0]:
        print(result)
        sublime.error_message("Can't initialize flow.")
      else:
        with open(flowconfig_file_path, 'r+', encoding="utf-8") as file:

      ... other code ...
```

Save it, then reopen Sublime Text 3, try to create again a javascript project and paste here the new Sublime Text console logs!

Thanks

**Comment by maprezentalok** [comment]
[False, '\nThis program is blocked by group policy, for more information contact Systems Administrator.']
error: Can't initialize flow.

Ok thanks, running Sublime Text as admin works. Also had to right to node to reach flow. False alarm :)

**Comment by pichillilorenzo** [comment]
No problem! Thank you @maprezentalok! 😄 

However I'm going to push a new commit soon (maybe tomorrow) with a complete plugin code refactoring (because now I'm using a "workaround" that I defined in the CONTRIBUTING.md 😞 that is very horrible) in order to allow people to understand better my code, so they could help me improve the plugin 😃.
