### ISSUE TITLE
Custom node path

### ISSUE THREAD

**Issue by dw72** [pichillilorenzo/JavaScriptEnhancements#4]
I use nodenv and your extension don't see node which is on my machine. Option to set custom node path will be nice.

**Comment by pichillilorenzo** [comment]
@dw72 

Yeah, I know. I'm already working on it because I have noticed this problem only now 😞 . 
There are problems with $PATH environment variable because python subprocess module doesn't load it from .bashrc or .profile! In fact I'm going to add a new "key-value" named "PATH" on the global settings of the plugin in which you can add paths that will be added to the subprocess session. Example for Linux with `nvm`:

```
{
  // ...

  "PATH": "/home/lorenzo/.nvm/versions/node/v9.2.0/bin",
  "node_js_custom_path": "node",
  "npm_custom_path": "npm",

  // ...
}
```

I'm going to release another version in very short time 👍 .

**Comment by pichillilorenzo** [comment]
@dw72 

I updated the plugin! Download the latest release and try again by setting the "PATH" of your binaries in the global settings of this plugin (`Preferences > Package Settings > JavaScript Enhancements > Settings`), like the example in the previous comment but using `nodenv`, and then restart!

If it doesn't work again, please post here the console logs of Sublime Text and your global settings!

Let me know!

**Comment by ChainsawBaby** [comment]
@pichillilorenzo I use nvm on mac, and I get this error in the log
```
v9.3.0
5.6.0
error: Error during installation: can not install the npm dependencies for JavaScript Enhancements.
```

And I've set custom PATH in the settings

**Comment by pichillilorenzo** [comment]
@ChainsawBaby could you try to add this line code after the 1229 line in the file _generated_2018_01_02_at_20_54_26.py in the main folder:

`print(result)`

Restart sublime and then copy and paste again here please. This time it need contain the error!

**Comment by tofuvn** [comment]
```
[False, "\nmodule.js:557\nthrow err;\n^\n\nError: Cannot find module '/home/thehovnpl/.config/sublime-text-3/Packages/JavaScript Enhancements/npm'\nat Function.Module._resolveFilename (module.js:555:15)\nat Function.Module._load (module.js:482:25)\nat Function.Module.runMain (module.js:701:10)\nat startup (bootstrap_node.js:194:16)\nat bootstrap_node.js:618:3"]
error: Error during installation: can not install the npm dependencies for JavaScript Enhancements.
```
i have the same problem

**Comment by pichillilorenzo** [comment]
@tofuvn if you go to the package folder and run the command `npm install`, does it work? Does it create the node_modules folder? Or it throws an error anyway??

**Comment by tofuvn** [comment]
![screenshot from 2018-01-02 23-11-59](https://user-images.githubusercontent.com/34548201/34502122-601fedf6-f012-11e7-88ae-e894febd8cd3.png)

**Comment by pichillilorenzo** [comment]
@tofuvn so I think the problem is not coming from my plugin but it is related to the permission about the files that npm is using! 

If you can, try to update the permission of your .config file like it says with `sudo chown ....`. Then uninstall the package and reinstall it! If think it could work now.

Let me know! Thanks 👍

**Comment by tofuvn** [comment]
![screenshot from 2018-01-03 00-12-25](https://user-images.githubusercontent.com/34548201/34503827-e7ca2fb6-f01a-11e7-9b03-c772d1859144.png)

**Comment by pichillilorenzo** [comment]
@tofuvn mmm try to reinstall node.js and npm (see this [guide](https://docs.npmjs.com/getting-started/fixing-npm-permissions)). Or use a Node Version Manager like `nvm`  or `nodenv` to install node and npm!

**Comment by dw72** [comment]
Ok i clone last master, set options like in this screenshot
![zrzut ekranu z 2018-01-03 08-40-28](https://user-images.githubusercontent.com/1017175/34512438-e2c46b7e-f062-11e7-8fd4-8a6d091bac9d.png)
and after that run ST and... have this error
![zrzut ekranu z 2018-01-03 08-39-08](https://user-images.githubusercontent.com/1017175/34512462-04abbd46-f063-11e7-92be-6bc1adeaf2f6.png)
when i try to open settings of your extension i have this
![zrzut ekranu z 2018-01-03 08-39-52](https://user-images.githubusercontent.com/1017175/34512476-15afdba4-f063-11e7-987a-c8ef4e8955d5.png)
but my permissions are ok
![zrzut ekranu z 2018-01-03 08-41-00](https://user-images.githubusercontent.com/1017175/34512498-3259c0e4-f063-11e7-96ce-2c2a57c6125c.png)
and manual install of extension deps is going ok
![zrzut ekranu z 2018-01-03 08-38-06](https://user-images.githubusercontent.com/1017175/34512513-494d5ad6-f063-11e7-8d78-77b75ee77436.png)

After that st runs without errors but opening settings from menu still gives me an error.

**Comment by ChainsawBaby** [comment]
@dw72 for the settings issue, rename to folder to "JavaScript Enhancements", notice the space there. That's where it's looking for the settings file. @pichillilorenzo have added this bit to the README

**Comment by pichillilorenzo** [comment]
@dw72 Did it work? So I can close this issue!

**Comment by dw72** [comment]
@pichillilorenzo It looks that is working now, and we can close this issue.

But in near feature you should try to correct automatic dependency installation :)

**Comment by pichillilorenzo** [comment]
@dw72 I already try to do `npm install` automatically during the plugin installation, but different people have different problems, for example the npm permission access error (EACCESS error), that is not a problem of my plugin, but in how node.js and npm are installed on the system.

However thank you for your support! 👍

**Comment by dw72** [comment]
I have this EACCESS error too, but manual install on the same account is working without any problems

**Comment by pichillilorenzo** [comment]
@dw72 So could you try to reinstall the plugin again with lastest release and then paste here the console logs of Sublime Text please? So maybe I could try to resolve the problem! Thanks again 😃

**Comment by dw72** [comment]
@pichillilorenzo there is the error from log:
```
[False, "\nmodule.js:538\nthrow err;\n^\n\nError: Cannot find module '/home/milley/.config/sublime-text-3/Packages/JavaScript Enhancements/npm'\nat Function.Module._resolveFilename (module.js:536:15)\nat Function.Module._load (module.js:466:25)\nat Function.Module.runMain (module.js:676:10)\nat startup (bootstrap_node.js:187:16)\nat bootstrap_node.js:608:3"]
error: Error during installation: can't install npm dependencies for JavaScript Enhancements plugin.

The error COULD be caused by the npm permission access (EACCES error), so in this case you need to repair/install node.js and npm in a way that doesn't require "sudo" command.

For example you could use a Node Version Manager, such as "nvm" or "nodenv".

Try to run "npm install" inside the package of this plugin to see what you get.
Package Control: Skipping automatic upgrade, last run at 2018-01-03 15:01:11, next run at 2018-01-03 16:01:11 or after
```

**Comment by pichillilorenzo** [comment]
@dw72 Mmm ok.. I will try to do something about that, or at least to write something about how to manage this problem 😞
