### ISSUE TITLE
Autocomplete fully disabled

### ISSUE THREAD

**Issue by hmazer** [pichillilorenzo/JavaScriptEnhancements#41]
I just installed JS Enhancements and everything it needs to work, as described on the wiki. Then I added it to an existing project (an express project).
The autocomplete function simply won't work. It's entirely disabled. Not just the JS Enhancements function, but even the default SublimeText autocomplete won't work.
It might be my fault but I couldn't get it to work.

### Specifications

- Sublime Text 3 build: 3143
- OS: OSX 10.13.3
- JavaScript Enhancements version: 0.16.1

BTW
Thanks for taking your time on developing this tool.

**Comment by pichillilorenzo** [comment]
Maybe could be errors in the Sublime Text console! please post here the console logs of Sublime Text when you open a javascript file of the project

**Comment by hmazer** [comment]
Maybe I didn't install flow correctly? See:

starting flow ide server: ['/Users/henrique/Library/Application Support/Sublime Text 3/Packages/JavaScript Enhancements/node_modules/.bin/flow', 'ide', '--protocol', 'very-unstable', '--from', 'sublime_text', '--root', '/Users/henrique/[deleted]']
flow ide stdout process ended.

**Comment by pichillilorenzo** [comment]
mmm it is weird.. the flow server isn't able to start. I need to investigate more on it! Anyway try to look if there exists already a flow process, then kill all flow processes and then try to reopen again Sublime Text!

**Comment by hmazer** [comment]
There isn't a flow processes running :/
Just to make sure: I don't have to manually install flow, right ?

**Comment by pichillilorenzo** [comment]
mmm ok! 
However you don't have to install them manually. All the dependencies need to be installed automatically by the plugin. If you have to install them manually, then there are problems with `npm`, but this is not your case 👍

**Comment by pichillilorenzo** [comment]
@hmazer try the new 0.16.11 version and let me know what you get in the Sublime Text console! Now you will get more information about the flow server I think 👍

**Comment by sdlambert** [comment]
I am getting the same error as @hmazer, I only have the one flow process but I get the same errors.

`/usr/bin/env: ‘node’: No such file or directory`

It's no surprise it can't find it there since I use nvm. The path in the config is correct:

```
{
    "PATH": ":/home/myusername/.nvm/versions/node/v9.8.0/bin",
    "enable_can_i_use_menu_option": false
}
```
Is the flow server looking in the right path?

**Comment by pichillilorenzo** [comment]
@sdlambert set `debug_mode: true` in the plugin option, then restart Sublime Text and open just a Javascript file. After that, open the Sublime Text console and post the logs here. Thanks!

**Comment by sdlambert** [comment]
```
starting flow ide server: ['/home/myusername/.config/sublime-text-3/Packages/JavaScript Enhancements/node_modules/.bin/flow', 'ide', '--protocol', 'very-unstable', '--from', 'sublime_text', '--root', '/home/myusername/.config/sublime-text-3/Packages/JavaScript Enhancements/src/libs/flow']
flow ide stdout process ended. Possible errors:
/usr/bin/env: ‘node’: No such file or directory
node '/home/myusername/.config/sublime-text-3/Packages/JavaScript Enhancements/node_modules/.bin/flow' ast --from sublime_text < /tmp/javascript_enhancements_p9bpso
```

**Comment by pichillilorenzo** [comment]
Ok.. Yeah I know about that but I can't close the flow server when you close Sublime, or, at least I don't know how to do it.. sublime API doesn't have any "event listener" when you close it, but only when you close a single view.

**Comment by pichillilorenzo** [comment]
@sdlambert in the sublime text console you also need to have a list of environment variables! That is why I asked you to set the debug mode, because I need to check if the path of your node is setted or not. Can you post it please?

**Comment by pichillilorenzo** [comment]
However now I have updated the plugin to 0.16.12. Try it and let me know if now it works!

**Comment by sdlambert** [comment]
The upgrade seems to have fixed it!

**Comment by Porock** [comment]
environ({'PATH': 'C:\\Program Files (x86)\\Common Files\\Intel\\Shared Libraries\\redist\\intel64\\compiler;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\Git\\cmd;C:\\Program Files\\nodejs\\;C:\\Program Files (x86)\\GtkSharp\\2.12\\bin;C:\\Program Files (x86)\\STMicroelectronics\\STM32 ST-LINK Utility\\ST-LINK Utility;C:\\Users\\IvanK\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\IvanK\\AppData\\Roaming\\npm;C:\\adb;C:\\Users\\IvanK\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\IvanK\\AppData\\Roaming\\npm;', 'FPS_BROWSER_APP_PROFILE_STRING': 'Internet Explorer', 'HOMEDRIVE': 'C:', 'ASL.LOG': 'Destination=file', 'APPDATA': 'C:\\Users\\IvanK\\AppData\\Roaming', 'PROGRAMFILES(X86)': 'C:\\Program Files (x86)', 'TMP': 'C:\\Users\\IvanK\\AppData\\Local\\Temp', 'WINDIR': 'C:\\WINDOWS', 'INTEL_DEV_REDIST': 'C:\\Program Files (x86)\\Common Files\\Intel\\Shared Libraries\\', 'PROCESSOR_REVISION': '3a09', 'OS': 'Windows_NT', 'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC', 'LOCALAPPDATA': 'C:\\Users\\IvanK\\AppData\\Local', 'PUBLIC': 'C:\\Users\\Public', 'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 58 Stepping 9, GenuineIntel', 'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files', 'PROCESSOR_LEVEL': '6', 'PROCESSOR_ARCHITECTURE': 'AMD64', 'ALLUSERSPROFILE': 'C:\\ProgramData', 'VBOX_MSI_INSTALL_PATH': 'C:\\Program Files\\Oracle\\VirtualBox\\', 'FPS_BROWSER_USER_PROFILE_STRING': 'Default', 'ONEDRIVE': 'C:\\Users\\IvanK\\OneDrive', 'PROGRAMW6432': 'C:\\Program Files', 'LOGONSERVER': '\\\\DESKTOP-L61TNC8', 'SESSIONNAME': 'Console', 'COMSPEC': 'C:\\WINDOWS\\system32\\cmd.exe', 'PROGRAMFILES': 'C:\\Program Files', 'USERPROFILE': 'C:\\Users\\IvanK', 'USERDOMAIN_ROAMINGPROFILE': 'DESKTOP-L61TNC8', 'HOMEPATH': '\\Users\\IvanK', 'GTK_BASEPATH': 'C:\\Program Files (x86)\\GtkSharp\\2.12\\', 'COMPUTERNAME': 'DESKTOP-L61TNC8', 'PROGRAMDATA': 'C:\\ProgramData', 'MIC_LD_LIBRARY_PATH': 'C:\\Program Files (x86)\\Common Files\\Intel\\Shared Libraries\\compiler\\lib\\mic', 'SYSTEMDRIVE': 'C:', 'NUMBER_OF_PROCESSORS': '4', 'PSMODULEPATH': 'C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules', 'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files', 'TEMP': 'C:\\Users\\IvanK\\AppData\\Local\\Temp', 'SYSTEMROOT': 'C:\\WINDOWS', 'USERNAME': 'IvanK', 'USERDOMAIN': 'DESKTOP-L61TNC8', 'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files'})
starting flow ide server: ['C:\\Users\\IvanK\\AppData\\Roaming\\Sublime Text 3\\Packages\\JavaScript Enhancements\\node_modules\\.bin\\flow.cmd', 'ide', '--protocol', 'very-unstable', '--from', 'sublime_text', '--root', 'C:\\Users\\IvanK\\AppData\\Roaming\\Sublime Text 3\\Packages\\JavaScript Enhancements\\src\\libs\\flow']
JavaScript Enhancements plugin version: 0.16.13
['node', '-v']
node.js version: v8.9.4
['node', '-v']
['npm', '-v']
npm version: 5.6.0
"C:\\Users\\IvanK\\AppData\\Roaming\\Sublime Text 3\\Packages\\JavaScript Enhancements\\node_modules\\.bin\\flow.cmd" "ast" "--from" "sublime_text" < "c:\\users\\ivank\\appdata\\local\\temp\\javascript_enhancements_t7xynp"
Package Control: Skipping automatic upgrade, last run at 2018-04-20 22:38:18, next run at 2018-04-20 23:38:18 or after

It is my console log in debug mode... autocomplete doesn't show enything

**Comment by DannyGarciaMartin** [comment]
I had to go into this directory /Users/danny/Library/Application Support/Sublime Text 3/Packages/JavaScript Enhancements, and I had to also run `npm install` _manually_ for the auto complete to show. Note: I never was able to get it to work for Sublime Text 3's built-in autocompletion modal.

So excited!! Thank you for all you do!
