### ISSUE TITLE
Plugin not honouring ST3 user settings - show_definitions

### ISSUE THREAD

**Issue by MuTLY** [pichillilorenzo/JavaScriptEnhancements#42]
### Expected Behavior
Using `"show_definitions": false` on Sublime Text 3 user settings to prevent the definitions popup to come up should not allow the popup to display when hovering the cursor over, e.g. a JS function.

### Actual Behavior
The popup shows up regardless of user settings.

### Sublime Text console logs 
None

### Screenshots
![1441e8494e0f47f306a9bee0d33d289914869806](https://user-images.githubusercontent.com/777006/37797569-f5b3dd5e-2df8-11e8-8c90-cfdcfe427fde.png)

- Sublime Text 3 build: 3143
- OS: Windows 10 Pro
- JavaScript Enhancements version: 0.16.11

**Comment by pichillilorenzo** [comment]
Now with the new version 0.16.12 it should work 👍
