### ISSUE TITLE
Feature Request - use npm packaged flow

### ISSUE THREAD

**Issue by speedboat** [pichillilorenzo/JavaScriptEnhancements#44]
It seems it is not possible to use project-level flow binary. Or am I missed something?

**Comment by speedboat** [comment]
I think it there should be user-defined (maybe non-default) option to enable project-level flow binary. Flow-s internal things changes much more often than external cli ones.

**Comment by pichillilorenzo** [comment]
@speedboat lol, I had already added this feature! Sorry! Just change the `flow_cli_custom_path` on the `project_settings.json` file. See here: https://github.com/pichillilorenzo/JavaScriptEnhancements/wiki/Project-settings
