### ISSUE TITLE
Flow not showing Error

### ISSUE THREAD

**Issue by thu-sama** [pichillilorenzo/JavaScriptEnhancements#53]
I installed the plugin by following wiki. But I'm not getting any error message boxes like in below screen shots.
I tried installing flow-bin globally `npm install -g flow-bin` but error boxes still does't show up.
I'm wondering am I missing some steps?

### Expected Behavior
![ScreenShot](https://camo.githubusercontent.com/e6ca9d236e2c1d07be84decc246d9b235e147bb1/68747470733a2f2f64726976652e676f6f676c652e636f6d2f75633f61757468757365723d302669643d317238494449744c3033745046774343735449645735347252706173636e484146266578706f72743d646f776e6c6f6164)

### Actual Behavior
![screen shot 2018-05-13 at 15 22 39](https://user-images.githubusercontent.com/11418765/39964532-86d64bfa-56c1-11e8-94c8-13fe7c851243.png)

### Sublime Text console logs 
reloading plugin JavaScript Enhancements.main
plugins loaded
starting flow ide server: ['node', '/Users/username/Library/Application Support/Sublime Text 3/Packages/JavaScript Enhancements/node_modules/.bin/flow', 'ide', '--protocol', 'very-unstable', '--from', 'sublime_text', '--root', '/Users/username/Desktop/test']

### Specifications

- Sublime Text 3 build: 3170
- OS: macOS High Sierra Version 10.13.4
- JavaScript Enhancements version: 0.16.15

**Comment by pichillilorenzo** [comment]
I have updated the [Errors and linting](https://github.com/pichillilorenzo/JavaScriptEnhancements/wiki/Errors-and-linting) wiki page!

**Comment by thu-sama** [comment]
Thanks, got it!

**Comment by redeemefy** [comment]
Is it a way to make flow to lint the entire project without adding `// @flow` within each file?

My `.flowconfig`

```config
[ignore]
<PROJECT_ROOT>/.je-project-settings/.*

[include]

[libs]

[lints]

[options]
all=true
emoji=true

[strict]
```
