### ISSUE TITLE
Some default key bindings are overridden by JavaScriptEnhancements

### ISSUE THREAD

**Issue by amsul** [pichillilorenzo/JavaScriptEnhancements#57]
Firstly, amazing package @pichillilorenzo! Love the work you've done here 🙇 

Now for the small annoyance I've been facing..

### Expected Behavior
The default key bindings that Sublime Text uses should work as expected.

### Actual Behavior
The following commands are used by Sublime Text:

- `super+alt+w`: for changing the search parameters to "whole word"
- `super+alt+s`: for saving all unsaved tabs

However, by adding JavaScriptEnhancements, they don't work as it has its own bindings for those keys.

There doesn't seem to be any easy way to remove this option without manually setting it back to the defaults.

Would you consider switching the key bindings to something not already in use?

**Comment by pichillilorenzo** [comment]
Thanks! Keymap changed to `super+alt+j` and `super+alt+h`! Now it shouldn't override the default key bindings! I'm going to release a new version with this fix now 👍

**Comment by amsul** [comment]
@pichillilorenzo awesome! Thanks for handling it so quickly 😄
