### ISSUE TITLE
Exception in thread DownloadCanIuseJsonData

### ISSUE THREAD

**Issue by bezdupel** [pichillilorenzo/JavaScriptEnhancements#58]
### Sublime Text console logs 

```
Exception in thread DownloadCanIuseJsonData:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "D:\Portables\SublimeText\Data\Packages\JavaScript Enhancements\src\commands\can_i_use\can_i_use.py", line 53, in donwload_can_i_use_json_data
    os.rename(path_to_test_can_i_use_data, path_to_can_i_use_data)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'D:\\Portables\\SublimeText\\Data\\Packages\\JavaScript Enhancements\\src\\commands\\can_i_use\\can_i_use_data.json'
```

### Steps to Reproduce the Problem

1. Run Sublime.
1. Open the console and see the error.

### Specifications

- Sublime Text 3 build: 3176 x64
- OS: Windows 10 Pro for Workstations x64
- JavaScript Enhancements version: 0.16.18

**Comment by pichillilorenzo** [comment]
Is this error breaking the plugin functionalities?

**Comment by bezdupel** [comment]
It's hard to say, because I do not use this feature. Just saw the error in the console and decided to create a new issue.

**Comment by pichillilorenzo** [comment]
Ok! Then in this case it is ok.. This happens sometimes when the plugin try to update the json file of "Can I Use" data :+1:
