### ISSUE TITLE
error when installing manually

### ISSUE THREAD

**Issue by 13husen** [pichillilorenzo/JavaScriptEnhancements#6]
i am using linux 18.1 serena 64 bit,but when i put the file in brow "browse package" i got alert : **Your architecture is not supported by this plugin. This plugin supports only 64bit architectures**,and i restart it,but there's still the same alert

**Comment by pichillilorenzo** [comment]
@13husen Try to run this code `import platform; platform.architecture()` in the console of Sublime Text and let me know what you get! Thanks!

**Comment by pichillilorenzo** [comment]
@13husen any news?

**Comment by 13husen** [comment]
sorry for late response @pichillilorenzo ,i test it and got the output : 

>import platform; platform.architecture()
> ('32bit', '')
so,i guess i installed the wrong sublime text huh ?

**Comment by pichillilorenzo** [comment]
@13husen Could be. Try to download the 64bit version of it and then install the latest version of this plugin 👍

**Comment by 13husen** [comment]
@pichillilorenzo  done :+1:  ,then i closed this issue
