### ISSUE TITLE
Plugin doesn't autocomplete from node_modules imports

### ISSUE THREAD

**Issue by nelsonvassalo** [pichillilorenzo/JavaScriptEnhancements#61]
### Expected Behavior
Autocomplete from node_modules

### Actual Behavior
Empty definitions and no autocomplete for node modules

### Steps to Reproduce the Problem

1. Hovering or hitting key combination for completion shows only `any => any`

### Specifications

- Sublime Text 3 build:  3176
- OS: Mac OS 10.13.5
- JavaScript Enhancements version: 0.16.20

**Comment by pichillilorenzo** [comment]
To get autocompletion from your imported files from node_modules, you need to download the flow type definitions (typescript works the same), see:https://github.com/pichillilorenzo/JavaScriptEnhancements/wiki/Adding-new-definitions-with-flow-typed

If the type definition is missing in the [official flow-typed repository](https://github.com/flowtype/flow-typed), then autocompletion will not show up because Flow cannot get it.

**Comment by nelsonvassalo** [comment]
Hi

Does that mean every single library needs its own Flow type definition?
Or is there s single Flow def for ‘node_modules’?

What about my custom modules, will they be autocompleted?

Thank you

**Comment by pichillilorenzo** [comment]
> Does that mean every single library needs its own Flow type definition?

Yes, for example if you are using "express" in a node.js app, you will need its flow type definition to get autocompletion

> What about my custom modules, will they be autocompleted?

technically, yes! But if they are in node_modules folder, then you need also here flow type definition

This is how flow (and typescript) works

**Comment by nelsonvassalo** [comment]
So if instead of laoding a big library, like say Three.js out of the modules and into my own source folder, they’d suddenly get autocomplete?

**Comment by nelsonvassalo** [comment]
So I came across a Typescript definitoon for these libraries. Any chance I can use that instead of the flow def?

**Comment by pichillilorenzo** [comment]
You need to install the Typescript plugin for Sublime to work with .ts files because this plugin works only with .js files! If you are working in a typescript project, then the Typescript plugin will do the job
