### ISSUE TITLE
TerminalView alternative.

### ISSUE THREAD

**Issue by pombadev** [pichillilorenzo/JavaScriptEnhancements#62]
As per in the wiki [os-supported-now](https://github.com/pichillilorenzo/JavaScriptEnhancements/wiki#os-supported-now) section, you mentioned:
> Has someone any advice or idea about that? Is there something similar to the TerminalView plugin for Windows?? Thanks!

Here's [**Terminus: _"The first cross platform terminal for Sublime"_**](https://github.com/randy3k/Terminus)

### Specifications

- Sublime Text 3 build: 3.1.1 (Build 3176)
- OS: Manjaro Linux 17.1.11
- JavaScript Enhancements version: 0.16.20

**Comment by pichillilorenzo** [comment]
Yes, I know about that! :+1:  I will add it when possible!

**Comment by pombadev** [comment]
Awesome, cheers!
