### ISSUE TITLE
It is uncompatible with the plugin sublimeCodeIntel

### ISSUE THREAD

**Issue by sven31316** [pichillilorenzo/JavaScriptEnhancements#74]
### Expected Behavior
hint as usual

### Actual Behavior
It is always blinking ,and I can't select the items ,as is show in the git above.

### Screenshots

http://sowcar.com/t6/682/1552566193x1699166072.gif

### Specifications

- Sublime Text 3 build:3.2
- OS:Windows10 1809 64bit
- JavaScript Enhancements version: 0.16.20

**Comment by ahmadsholehin** [comment]
Would really appreciate if there are settings within JSE that we can toggle. E.g. switch on or off linting and hover popups via settings.
