### ISSUE TITLE
Publish it for package Control Installation!

### ISSUE THREAD

**Issue by minimallinux** [pichillilorenzo/JavaScriptEnhancements#8]
Hi, looks good but hard to install manually, when is it going to be published for installation via PackageControl? Thanks

**Comment by pichillilorenzo** [comment]
They still do not accept my [pull request](https://github.com/wbond/package_control_channel/pull/6839) to package control repo yet 😞 . Like they said [here](https://packagecontrol.io/docs/submitting_a_package#Step_8):

> Please be patient as your pull request is reviewed. We review changes to try and help prevent duplicate packages, spot common errors and help improve the package experience for users.

**Comment by pichillilorenzo** [comment]
However it will require the same things with package control! I mean settings for `PATH`, node.js, etc., in case of problems!

**Comment by pichillilorenzo** [comment]
Done! 😄
