### ISSUE TITLE
Can't install NPM dependencies error on open of Sublime.

### ISSUE THREAD

**Issue by tr1s** [pichillilorenzo/JavaScriptEnhancements#9]
I know the fix is in the Readme but I don't understand it. 

I tried googling how to find the node path, and when I type `npm config get prefix` all I get is /usr/local/. Looks way different than the example. 

How do I find the right path?

Thanks

**Comment by pichillilorenzo** [comment]
@tr1s Could you paste here the the console logs of Sublime Text please?? Maybe there is also another error! 
However, if you are using **nvm**, try to run `nvm which current`, otherwise try `which node` in your terminal.

**Comment by tr1s** [comment]
@pichillilorenzo I don't have nvm, I have npm. How do I check console logs of Sublime Text?

<img width="418" alt="screen shot 2018-01-08 at 1 04 46 pm" src="https://user-images.githubusercontent.com/19172250/34684942-c9cafa3c-f474-11e7-84a2-984d17a6ac31.png">

**Comment by pichillilorenzo** [comment]
@tr1s `View > Show Console`, then copy and paste here the logs. Thanks!

**Comment by pichillilorenzo** [comment]
See also #4

**Comment by pichillilorenzo** [comment]
@tr1s I released a new version. Try it and let me know!

**Comment by tr1s** [comment]
Hey @pichillilorenzo , I installed your new one and got this pop-up. 

<img width="480" alt="screen shot 2018-01-08 at 5 46 24 pm" src="https://user-images.githubusercontent.com/19172250/34696352-78b97e48-f49c-11e7-97be-41854dfaad91.png">

I just went to the node site and downloaded the latest version and everything's fine and completions are showing now! I guess I wasn't fully updated to the latest node.js

Will I keep having this problem when Node updates? Also is NVM something I should be using all the time instead of NPM? I don't fully understand it, like is it a replacement for NPM all together? Thank you for your help!

**Comment by pichillilorenzo** [comment]
@tr1s 👍 

> Will I keep having this problem when Node updates?

I think you will be fine if you have at least 6.0.0. You said that you have the latest one so it is ok! 👍 

> Also is NVM something I should be using all the time instead of NPM?

NVM is a:

> Node Version Manager - Simple bash script to manage multiple active node.js versions

If you want use it go to: [https://github.com/creationix/nvm](https://github.com/creationix/nvm), but it is **not required** to use my plugin! Just your choice 😄 

So Could I close this issue now?

**Comment by tr1s** [comment]
Sounds good, yup close the issue @pichillilorenzo thanks!
